# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'FishHookProtect.xcworkspace'

target 'FishHookProtect' do
  use_frameworks!
  pod 'fishhookProtection', '0.4.0'
end

target 'InsertDyld' do
    use_frameworks! 
    pod 'fishhookProtection', '0.4.0'
    project 'InsertDyld/InsertDyld.xcodeproj'
end
